apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend-deployment
  labels:
    app: notes-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
    
      containers:
        - name: notes-backend
          image: ishannikeshala99/notes-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/nedb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-username
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update

---
apiVersion: v1
kind: Service
metadata:
  name: notes-backend-service
spec:
  selector:
    app: notes-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30009
  type: NodePort