apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  next_public_api_url: http://192.168.49.2:30007


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-api-configmap
data:
  api_url: http://notes-backend-service:8080