apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend-deployment
  labels:
    app: notes-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
        - name: notes-backend
          image: ishannikeshala99/notes-backend:latest
          ports:
            - containerPort: 8080
      env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysqldb-configmap
              key: dbname

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysqldb-secret
              key: username

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
            name: mysqldb-secret
            key: password

        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
---
apiVersion: v1
kind: Service
metadata:
  name: notes-backend-service
spec:
  selector:
    app: notes-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP