apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend-deployment
  labels:
    app: notes-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notess-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
        - name: notes-backend
          image: notes-backend:latest
          ports:
          - containerPort: 8080
          env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
             configMapKeyRef:
               name: mysqldb-configmap
               key: database_url  
          - name: SPRING_DATASOURCE_USERNAME
            value: ne_user
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
             secretKeyRef:
               name: mysqldb-secret
               key: mysql-root-password  
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: update     

---
apiVersion: v1
kind: Service
metadata:
  name: notes-backend-service
spec:
  selector:
    app: notes-backend
  ports:
   - port: 8080
     targetPort: 8080
  