apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-frontend-deployment
  labels:
    app: note-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-frontend
  template:
    metadata:
      labels:
        app: note-frontend
    spec:
      containers:
        - name: note-frontend
          image: note-frontend:latest
          ports:
          - containerPort: 3000
          env:
          - name: NEXT_PUBLIC_API_URL
            valueFrom:
             configMapKeyRef:
               name: backend-configmap
               key: backend_url

---
apiVersion: v1
kind: Service
metadata:
  name: note-frontend-service
spec:
  type: NodePort
  selector:
    app: note-frontend
  ports:
   - port: 3000
     targetPort: 3000
     nodePort: 30008
  