apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-frontend
  template:
    metadata:
      labels:
        app: notes-frontend
        tier: notes-frontend
    spec:
      containers:
        - name: notes-frontend
          image: ishannikeshala99/notes-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # env:
          # - name: NEXT_PUBLIC_API_URL
          #   value: '/'

---
apiVersion: v1
kind: Service
metadata:
  name: notes-frontend
spec:
  type: ClusterIP
  selector:
    app: notes-frontend
    tier: notes-frontend
  ports:
    - port: 80
      targetPort: 3000